site_name: MC Launcher docs
theme:
  name: material
  palette:
    scheme: preference
    primary: green
    accent: light green
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
repo_url: https://github.com/MMK21Hub/MCL-docs
repo_name: MMK21Hub/MCL-docs
copyright: This unofficial site is not associated/approved by Mojang.
markdown_extensions:
  - toc:
      permalink: true
